### ISSUE TITLE
Aumentar Punto a una tercera coordenada

### ISSUE THREAD

**Issue by RealityMistic** [drachodran/IWVG.SwC.CesarGayo#1]
[Ver Wiki sobre Ampliación del Proyecto](https://github.com/drachodran/IWVG.SwC.CesarGayo/wiki)

**Comment by manupuchades** [comment]
El lunes por la tarde/noche estará lista

**Comment by RealityMistic** [comment]
Se da por cerrada por encargo duplicado. Error del arquitecto.
