### ISSUE TITLE
Ampliación de la clase fracción: isEquivalent

### ISSUE THREAD

**Issue by RealityMistic** [drachodran/IWVG.SwC.CesarGayo#3]
[Ver Wiki sobre Ampliación del Proyecto](https://github.com/drachodran/IWVG.SwC.CesarGayo/wiki)

**Comment by ATorreclla** [comment]
He tenido problemas en esta issue#3 por excesiva cantidad de horas
de trabajo. Los problemas han sido de configuración en mi equipo.

**Comment by RealityMistic** [comment]
Es necesario repetir la modificación y la fusión con la rama develop. He hecho reset hasta el commit de develop y de master previo a tus modificaciones. Por favor repite ambas fusiones por separado siguiendo la estructura de mensaje convencional que te expliqué en clase. Tienes la foto del comando. Gracias
