### ISSUE TITLE
Poder modificar las coordenadas de la clase Punto

### ISSUE THREAD

**Issue by RealityMistic** [drachodran/IWVG.SwC.CesarGayo#4]
[Ver Wiki sobre Ampliación del Proyecto](https://github.com/drachodran/IWVG.SwC.CesarGayo/wiki)

**Comment by RealityMistic** [comment]
Es necesario repetir la modificación y la fusión con la rama develop. He hecho reset hasta el commit de develop y de master previo a tus modificaciones.

**Comment by ATorreclla** [comment]
Se repite la fusión. Los problemas que ha habido han sido por defecto de la configuración de mi equipo.
Se pudieron solucionar a tiempo, antes de la fecha maxima.
